version: '3.8'

services:
  app:
    build:
      context: .
    image: minicase:1.0
    container_name: minicase_
    ports:
     - "8080:3000"
    volumes:
    - .:/usr/src/app
    networks:
      - minhaRede

  db:
    image: mysql:8.0
    container_name: minicase_DB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minhaRede

volumes:
  mysql_data:

networks:
  minhaRede:
    driver: bridge
